import '../styles/globals.css'
import {Inter} from 'next/font/google'
import Header from "@/components/header";
import {getServerSession} from "next-auth";
import SessionProvider from "@/components/provider/session-provider";


const inter = Inter({subsets: ['latin']})
export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({children}) {

    const session = await getServerSession()

    console.log(session)

    return (
        <html lang="en" >
            <body className={inter.className} >
                <SessionProvider session={session} >
                    <Header />
                    {children}
                </SessionProvider >
            </body >
        </html >
    )
}
